# Generated by Django 3.2.6 on 2021-08-14 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='text',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='url',
        ),
        migrations.AddField(
            model_name='blogs',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
