# Generated by Django 3.2.6 on 2021-08-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='desription',
            field=models.CharField(max_length=300),
        ),
    ]
